[[redirects]]
  from = "/policies/governance"
  to = "/about/governance"

[[redirects]]
  from = "/policies/transparency"
  to = "/about/governance"

[[redirects]]
  from = "/tools"
  to = "/products"

[[redirects]]
  from = "/tools/*"
  to = "/products/:splat"

[build]
  node_version = "18"
